version: '3'

networks:
  hadoop36:
    external:
      name: hadoop36

services:
  sparkmaster:
    image: koichiroiijima/spark:20191104
    domainname: hadoop36
    hostname: sparkmaster
    networks:
      - hadoop36
    volumes:
      - ./etc:/opt/hadoop/etc:z
    container_name: 'sparkmaster'
    ports:
      - "7077:7077"
      - "4040:4040"
      - "18080:18080"
      - "6066:6066"
      - "28080:8080"
    command: ["sleep", "infinity"]
